package:
  name: udnn
  version: 0.1

source:
  url: https://files.pythonhosted.org/packages/c4/f2/7fef978b0822a448c4be11851452cdb49d629412f4c0e5f2fb3dcfd262c1/udnn-0.0.1.tar.gz
  sha256: 1e0d57e0dfa82203fdb1ffe3edbea281b4a51d3e7a17f1da654be6ecd353aaad

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.6.4
    - pytorch >=0.4
    - numpy
    - h5py
    - pillow

test:
  imports:
    - udnn

about:
  home: https://github.com/DimitriosBellos/UDNN
  license: Apache 2.0
  summary: A Convolutional Neural Network for fast upscaling of low-resolution sinograms in x-ray CT time-series

extra:
  recipe-maintainers:
    DimitriosBellos
